//
// Generated file, do not edit! Created by opp_msgc 4.4 from apps/BATControl.msg.
//

#ifndef _BATCONTROL_M_H_
#define _BATCONTROL_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>apps/BATControl.msg</tt> by opp_msgc.
 * <pre>
 * enum MessageType1
 * {
 *     CONT_CHARGE = 1;
 *     CONT_DISCHARGE = 2;
 *     CONT_IDLE = 3;   
 * }
 * </pre>
 */
enum MessageType1 {
    CONT_CHARGE = 1,
    CONT_DISCHARGE = 2,
    CONT_IDLE = 3
};

/**
 * Class generated from <tt>apps/BATControl.msg</tt> by opp_msgc.
 * <pre>
 * packet
 * BATControl
 * {
 *     int type @enum(MessageType1);
 *     string source;
 *     simtime_t time;
 *     double var ;
 *     double kw;
 *     double voltage;
 * }
 * </pre>
 */
class BATControl : public ::cPacket
{
  protected:
    int type_var;
    opp_string source_var;
    simtime_t time_var;
    double var_var;
    double kw_var;
    double voltage_var;

  private:
    void copy(const BATControl& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BATControl&);

  public:
    BATControl(const char *name=NULL, int kind=0);
    BATControl(const BATControl& other);
    virtual ~BATControl();
    BATControl& operator=(const BATControl& other);
    virtual BATControl *dup() const {return new BATControl(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getType() const;
    virtual void setType(int type);
    virtual const char * getSource() const;
    virtual void setSource(const char * source);
    virtual simtime_t getTime() const;
    virtual void setTime(simtime_t time);
    virtual double getVar() const;
    virtual void setVar(double var);
    virtual double getKw() const;
    virtual void setKw(double kw);
    virtual double getVoltage() const;
    virtual void setVoltage(double voltage);
};

inline void doPacking(cCommBuffer *b, BATControl& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, BATControl& obj) {obj.parsimUnpack(b);}


#endif // _BATCONTROL_M_H_
